name: Setup Terraform

on: [workflow_call]

jobs:
  setup-terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"