name: Terraform
run-name: Terraform workflow
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  terraform:
    name: TF
    uses: fabrinator/actions/.github/workflows/terraform.yaml@main
    with:
      terraform_version: "1.9.2"
    secrets: inherit
